parameters:
#    project_name_admin.example.class: ProjectBundle\Bundle\AdminBundle\Example

services:
#    project_name_admin.example:
#        class: %project_name_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
