parameters:

  controller_listener.class: ProjectBundle\Bundle\CoreBundle\EventListener\ControllerListener
  request_listener.class: ProjectBundle\Bundle\CoreBundle\EventListener\RequestListener

services:

  controller_listener:
    class: %controller_listener.class%
    arguments: [@service_container]
    tags:
      -   { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

  request_listener:
    class: %request_listener.class%
    arguments: [@service_container]
    tags:
      -   { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

  acme.twig.ProjectBundle_extension:
          class: ProjectBundle\Bundle\CoreBundle\Twig\ProjectBundleExtension
          tags:
              - { name: twig.extension }

